# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  cell,
}: let
  lib = inputs.nixpkgs.lib // builtins;
in {
  imports = [
    inputs.nixos-hardware.nixosModules.common-cpu-intel
    inputs.nixos-hardware.nixosModules.common-gpu-intel
    inputs.nixos-hardware.nixosModules.common-gpu-intel
    inputs.nixos-hardware.nixosModules.common-pc-laptop
    inputs.nixos-hardware.nixosModules.common-pc-laptop-ssd
  ];
  # Solution to rcu_sched freezing
  boot.kernelParams = ["acpi_rev_override"];

  # This will save you money and possibly your life!
  services.thermald.enable = lib.mkDefault true;
  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  #boot.kernelModules = ["kvm-intel" "amdgpu"];
  #boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/347c9a30-d22d-467a-b5e2-b54d3e580686";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";
    fsType = "vfat";
  };

  swapDevices = [];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableRedistributableFirmware = true;
}
